#!/bin/sh
#sVer=$(date +%Y%m%d-%k.%M)
sVer=$(date +%Y%m%d)
echo "1.0-$sVer" > ../1.Version.txt
sFolder="urltonix"
echo "Publishing revision $sVer"
cd ~/Projects
rm -Rvf $sFolder-$sVer
mkdir $sFolder-$sVer
cp -R --no-dereference $sFolder/* $sFolder-$sVer
rm $sFolder-$sVer/src/release
rm $sFolder-$sVer/src/*~
rm $sFolder-$sVer/*~
rm $sFolder-$sVer/src/UniWinForms.cs
cp ~/Projects/UniWinForms/src/UniWinForms.cs $sFolder-$sVer/src
cp ~/Projects/UniWinForms/src/UniWinForm.cs $sFolder-$sVer/src
cp ~/Projects/UniWinForms/src/Chunker.cs $sFolder-$sVer/src
rm $sFolder-$sVer/bin/lib-$sFolder
zip -r $sFolder-$sVer.zip $sFolder-$sVer
rm -Rvf $sFolder-$sVer
mkdir ~/Documents/www/expertmultimedia/orangejuice/releases/$sFolder
mv -f $sFolder-$sVer.zip ~/Documents/www/expertmultimedia/orangejuice/releases/$sFolder/
echo
echo "Finished."
